// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class AchievementNhuNq
{
    public int AchievementNhuNqid { get; set; }

    public string AchievementName { get; set; }

    public string Description { get; set; }

    public string CriteriaType { get; set; }

    public double CriteriaValue { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<UserAchievementNhuNq> UserAchievementNhuNqs { get; set; } = new List<UserAchievementNhuNq>();
}