// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class BlogPostsAnVt
{
    public int BlogPostsAnVtid { get; set; }

    public int UserId { get; set; }

    public int? PlanId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Category { get; set; }

    public string Tags { get; set; }

    public bool IsPublic { get; set; }

    public int? ViewsCount { get; set; }

    public int? LikesCount { get; set; }

    public int? CommentsCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual QuitPlansAnhDtn Plan { get; set; }

    public virtual SystemUserAccount User { get; set; }
}