// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class ChatsLocDpx
{
    public int ChatsLocDpxid { get; set; }

    public int UserId { get; set; }

    public int CoachId { get; set; }

    public string Message { get; set; }

    public string SentBy { get; set; }

    public string MessageType { get; set; }

    public bool IsRead { get; set; }

    public string AttachmentUrl { get; set; }

    public DateTime? ResponseTime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual CoachesLocDpx Coach { get; set; }

    public virtual SystemUserAccount User { get; set; }
}