// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class LeaderboardsDuongLnt
{
    public int LeaderboardsDuongLntid { get; set; }

    public int UserId { get; set; }

    public int? PlanId { get; set; }

    public int? DaySmokeFree { get; set; }

    public double? MoneySave { get; set; }

    public int? RankPosition { get; set; }

    public int? TotalAchievements { get; set; }

    public double? ProgressScore { get; set; }

    public string Note { get; set; }

    public int? StreakCount { get; set; }

    public int? CommunityContribution { get; set; }

    public bool? IsTopRanked { get; set; }

    public DateTime? LastUpdate { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual QuitPlansAnhDtn Plan { get; set; }

    public virtual SystemUserAccount User { get; set; }
}