// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class MembershipPlansAnhDtn
{
    public int MembershipPlansAnhDtnid { get; set; }

    public string PlanName { get; set; }

    public string Description { get; set; }

    public double Price { get; set; }

    public int DurationDays { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<QuitPlansAnhDtn> QuitPlansAnhDtns { get; set; } = new List<QuitPlansAnhDtn>();
}