// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class ProgressRecordsHoangPx
{
    public int ProgressRecordsHoangPxid { get; set; }

    public int UserId { get; set; }

    public int? SupportMethodId { get; set; }

    public int? CigarettesSmoked { get; set; }

    public string HealthStatus { get; set; }

    public double? MoneySaved { get; set; }

    public int? DaysSmokeFree { get; set; }

    public DateTime RecordedAt { get; set; }

    public string Mood { get; set; }

    public bool HadCraving { get; set; }

    public int? CravingLevel { get; set; }

    public string Notes { get; set; }

    public DateTime? ModifiedAt { get; set; }

    public virtual SupportMethodsHoangPx SupportMethod { get; set; }

    public virtual SystemUserAccount User { get; set; }
}