// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class QuitPlansAnhDtn
{
    public int QuitPlansAnhDtnid { get; set; }

    public int UserId { get; set; }

    public int? MembershipPlanId { get; set; }

    public string Reason { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? ExpectedQuitDate { get; set; }

    public int? DailyCigaretteTarget { get; set; }

    public int? WeeklyCheckinFrequency { get; set; }

    public string MotivationalMessage { get; set; }

    public string HealthGoals { get; set; }

    public double? BudgetSavingGoal { get; set; }

    public bool ReceiveMotivationReminder { get; set; }

    public bool IsCustomizedPlan { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<BlogPostsAnVt> BlogPostsAnVts { get; set; } = new List<BlogPostsAnVt>();

    public virtual ICollection<LeaderboardsDuongLnt> LeaderboardsDuongLnts { get; set; } = new List<LeaderboardsDuongLnt>();

    public virtual MembershipPlansAnhDtn MembershipPlan { get; set; }

    public virtual SystemUserAccount User { get; set; }
}