// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class SupportMethodsHoangPx
{
    public int SupportMethodsHoangPxid { get; set; }

    public string MethodName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ProgressRecordsHoangPx> ProgressRecordsHoangPxes { get; set; } = new List<ProgressRecordsHoangPx>();
}