// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class SystemUserAccount
{
    public int UserAccountId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmployeeCode { get; set; }

    public int RoleId { get; set; }

    public string RequestCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ApplicationCode { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BlogPostsAnVt> BlogPostsAnVts { get; set; } = new List<BlogPostsAnVt>();

    public virtual ICollection<ChatsLocDpx> ChatsLocDpxes { get; set; } = new List<ChatsLocDpx>();

    public virtual ICollection<LeaderboardsDuongLnt> LeaderboardsDuongLnts { get; set; } = new List<LeaderboardsDuongLnt>();

    public virtual ICollection<ProgressRecordsHoangPx> ProgressRecordsHoangPxes { get; set; } = new List<ProgressRecordsHoangPx>();

    public virtual ICollection<QuitPlansAnhDtn> QuitPlansAnhDtns { get; set; } = new List<QuitPlansAnhDtn>();

    public virtual ICollection<UserAchievementNhuNq> UserAchievementNhuNqs { get; set; } = new List<UserAchievementNhuNq>();
}