// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmokeQuit.Repositories.AnVT.Models;

public partial class UserAchievementNhuNq
{
    public int UserAchievementNhuNqid { get; set; }

    public int UserId { get; set; }

    public int AchievementId { get; set; }

    public DateTime AchievedAt { get; set; }

    public bool Shared { get; set; }

    public bool NotificationSent { get; set; }

    public int? RewardPoints { get; set; }

    public int? CommentCount { get; set; }

    public int? LikeCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual AchievementNhuNq Achievement { get; set; }

    public virtual SystemUserAccount User { get; set; }
}